apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project
  namespace: argocd
spec:
  description: Two-tier demo project with MySQL
  sourceRepos:
    - 'https://github.com/RamitTechnical/argocd-two-tier-project.git'
  destinations:
    - namespace: chat-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    
    - group: ""
      kind: Secret
    - group: ""
      kind: Pod
    - group: ""
      kind: Service
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: ReplicaSet

