apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project
  namespace: argocd
spec:
  description: Two-tier demo project with MySQL
  sourceRepos:
    - '*'
  destinations:
    - namespace: demo-namespace
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: PersistentVolumeClaim
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Pod
    - group: ""
      kind: Service
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: ReplicaSet
    - group: "batch"
      kind: Job
    - group: "batch"
      kind: CronJob
